export const data = [
  { id: "a3f9d2", name: "Ba", type: "GIA_DINH", message: "" },
  { id: "c5b8e1", name: "Mẹ", type: "GIA_DINH", message: "" },
  { id: "d72a1c", name: "Anh 2", type: "GIA_DINH", message: "" },
  { id: "e94c0b", name: "Dũ", type: "GIA_DINH", message: "" },
  { id: "b62f9e", name: "Đức Bảo", type: "ANH_IU", message: "" },
  { id: "f83a2b", name: "Quang Thành", type: "GAI_RG", message: "" },
  { id: "a1e9f3", name: "Gia Hân", type: "GAI_RG", message: "" },
  { id: "b4c5a7", name: "Ngọc Như", type: "GAI_RG", message: "" },
  { id: "d3a7e9", name: "Lan Anh", type: "GAI_RG", message: "" },
  { id: "e2b9f5", name: "Kiều Anh", type: "GAI_RG", message: "" },
  { id: "f4c8b1", name: "Lâm Chí Khang", type: "GAI_12H", message: "" },
  { id: "a6e2d4", name: "Hồng Thảo", type: "GAI_12H", message: "" },
  { id: "b9f5a2", name: "Thùy Ngân", type: "GAI_12H", message: "" },
  { id: "c2a4f7", name: "Hà Trang", type: "F_CODE", message: "" },
  { id: "d5b8c3", name: "Công Minh", type: "F_CODE", message: "" },
  { id: "e6f1a9", name: "Gia Linh", type: "F_CODE", message: "" },
  { id: "f7a3d2", name: "Minh Khôi", type: "F_CODE", message: "" },
  { id: "a8c5e4", name: "Như Nguyên", type: "F_CODE", message: "" },
  { id: "b1d6f8", name: "Dương Hoàng Nam", type: "DO_AN", message: "" },
  { id: "c4e9b2", name: "Văn Phú Hòa", type: "DO_AN", message: "" },
  { id: "d7a2c5", name: "Trần Tấn Thành", type: "DO_AN", message: "" },
  { id: "e9f4a3", name: "Chị Hạnh", type: "GNZ", message: "" },
  { id: "f2b7c6", name: "Nguyễn Nhi", type: "GNZ", message: "" },
  { id: "a3e8d1", name: "Tuyết Nhi", type: "GNZ", message: "" },
  { id: "b5f9a4", name: "Hoàng Yến", type: "GNZ", message: "" },
  { id: "c8a2e7", name: "Bảo Thư", type: "GNZ", message: "" },
  { id: "d9b3f1", name: "Thầy LVT", type: "IELTS", message: "" },
  { id: "e1c5a8", name: "Chị Mint", type: "IELTS", message: "" },
  { id: "f3a9b7", name: "Chị Mía", type: "IELTS", message: "" },
  { id: "a4e2f5", name: "Minh Ngọc", type: "IELTS", message: "" },
  { id: "b6c3a9", name: "Trí Phan", type: "IELTS", message: "" },
  { id: "c7f8b4", name: "Thành Nhân", type: "IELTS", message: "" },
  { id: "d1a9e6", name: "Châu Anh", type: "IELTS", message: "" },
  { id: "e5b2f9", name: "Quỳnh Giao", type: "IELTS", message: "" },
  { id: "f8a3c1", name: "Thắm", type: "IELTS", message: "" },
  { id: "a9d5e7", name: "Quốc Tuấn", type: "IELTS", message: "" },
  { id: "b2f4c8", name: "Quốc Đạt", type: "IELTS", message: "" },
  { id: "c3a7b1", name: "Khánh My", type: "NAB", message: "" },
  { id: "d4b8f6", name: "Thảo Đào", type: "NAB", message: "" },
  { id: "e7c1a5", name: "Lương Bùi", type: "NAB", message: "" },
  { id: "f9a4d2", name: "Mẫn Nhi", type: "NAB", message: "" },
  { id: "a2e5f3", name: "Bảo Anh", type: "NAB", message: "" },
  { id: "b7c9a1", name: "Khang Lê", type: "BAN", message: "" },
];

export enum GuestType {
  GIA_DINH = "GIA_DINH",
  ANH_IU = "ANH_IU",
  GAI_RG = "GAI_RG",
  GAI_12H = "GAI_12H",
  F_CODE = "F_CODE",
  DO_AN = "DO_AN",
  GNZ = "GNZ",
  IELTS = "IELTS",
  NAB = "NAB",
  BAN = "BAN",
}
